### ISSUE TITLE
Mc Versions and Java Info

### ISSUE THREAD

**Issue by TheCiROMG** [DavidS-Repo/chunker#1]
PaperMC has begun supporting Java 21 starting with Minecraft version 1.20.6. 1.20.6 to latest

If you're running this version or later, you will need to use Java 21 for compatibility. 

This change is due to recent updates in the Minecraft ecosystem that require newer Java versions for optimal performance and security​ 

([PaperMC](https://papermc.io/))​ ([PaperMC](https://forums.papermc.io/threads/paper-velocity-1-20-6.1152/)).

And publish the whole code if possible, and if you want to do it, so that users support your project, there was one before with PaperMC support and its optimizations but it is abandoned and its code is not released :c

**Comment by DavidS-Repo** [comment]
Hi TheCiROMG,

Thank you for your feedback and interest in the project!

I'm a bit unclear about what you're specifically requesting. Just to clarify:

- The Chunker plugin is already compiled with Java 21, and it's intended to be compatible with Minecraft versions starting from 1.20.6, as PaperMC now requires Java 21 for these versions.
- The full source code for the project is available in the [GitHub repository](https://github.com/DavidS-Repo/chunker/tree/main/Chunker).

I also wanted to mention that if you're referring to the absence of PaperLib, this was a deliberate change. I'm now directly using the updated Bukkit.World class provided by Paper and its forks, which includes the asynchronous chunk loading method, instead of relying on PaperLib.

If there's something specific you're looking for, such as adding information about the Java version required to compile the plugin or clarifying which Minecraft versions are supported, please let me know! I'm happy to make any necessary updates or clarifications.
